---
# tasks file for role_tomcat

- name: add a group tomcat 
  group:
    name: tomcat

- name: add tomcat user
  user:
    name: tomcat
    group: tomcat
    home: /user/share/tomcat
    createhome: no

- name: create tomcat directory
  file:
    name: /opt/tomcat
    state: directory
  
- name: download & unarchive
  unarchive:
    src: https://www-eu.apache.org/dist/tomcat/tomcat-9/v9.0.30/bin/apache-tomcat-9.0.30.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: create a tomcat file service 
  file:
    path: /etc/systemd/system/tomcat.service
    state: touch

- name: config service
  lineinfile:
    path:  /etc/systemd/system/tomcat.service
    line:  "{{ item }}"
  loop:  "{{ list }}"

- name: Gestion du service
  systemd:
   daemon_reload: yes

- name: Start and enable Tomcat service
  systemd:
    name: tomcat
    state: started
    enabled: true

  



- #name: Gestion du service
  #systemd:
   #daemon_reload: yes

- #name: Start and enable Tomcat service
  #systemd:
   # name: tomcat
    #state: started
    #enabled: true





























